services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: photoshnaya_bot:prod
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      token: ${token}
      ps_url: ${ps_url}
