services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: photoshnaya_bot:test
    env_file:
      - .env
    environment:
      testps_url: ${testps_url:-postgresql+psycopg://postgres:postgres@db:5432/postgres}
    command: ["sh", "-c", "cd app && uv run --no-sync pytest tests -v"]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
