CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    full_name TEXT,
    telegram_id BIGINT NOT NULL,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "group" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    telegram_id BIGINT NOT NULL,
    vote_in_progress BOOLEAN NOT NULL DEFAULT FALSE,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contest (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_name TEXT NOT NULL,
    contest_duration_sec INTEGER NOT NULL,
    link_to_results TEXT,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    group_id INTEGER NOT NULL REFERENCES "group" (id)
);

CREATE TABLE IF NOT EXISTS photo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    telegram_type VARCHAR(15) NOT NULL DEFAULT 'photo',
    user_id INTEGER NOT NULL REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS group_photo (
    photo_id INTEGER NOT NULL REFERENCES photo (id),
    group_id INTEGER NOT NULL REFERENCES "group" (id),
    PRIMARY KEY (photo_id, group_id)
);

CREATE TABLE IF NOT EXISTS group_user (
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    group_id INTEGER NOT NULL REFERENCES "group" (id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS group_admin (
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    group_id INTEGER NOT NULL REFERENCES "group" (id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS photo_like (
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    photo_id INTEGER NOT NULL REFERENCES photo (id),
    PRIMARY KEY (user_id, photo_id)
);

CREATE TABLE IF NOT EXISTS tmp_photo_like (
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    photo_id INTEGER NOT NULL REFERENCES photo (id),
    PRIMARY KEY (user_id, photo_id)
);

CREATE TABLE IF NOT EXISTS contest_user (
    contest_id INTEGER NOT NULL REFERENCES contest (id),
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    PRIMARY KEY (contest_id, user_id)
);

CREATE TABLE IF NOT EXISTS contest_winner (
    contest_id INTEGER NOT NULL REFERENCES contest (id),
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    PRIMARY KEY (contest_id, user_id)
);

CREATE TABLE IF NOT EXISTS contest_participant (
    contest_id INTEGER NOT NULL REFERENCES contest (id),
    user_id INTEGER NOT NULL REFERENCES "user" (id),
    PRIMARY KEY (contest_id, user_id)
);
